/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.1 and the Signal Processing Toolbox 7.3.
 * Generated on: 18-Jan-2019 11:18:01
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 5
 * Denominator Length  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "imu_convert.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\matlab\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */

Diff_RAW Diff_GX = {{0.206572, 0.413144, 0.206572}, {1, -0.369527, 0.195816}},
				 Diff_GY = {{0.206572, 0.413144, 0.206572}, {1, -0.369527, 0.195816}},
				 Diff_GZ = {{0.206572, 0.413144, 0.206572}, {1, -0.369527, 0.195816}};

//Diff_RAW Diff_GX={{0.067455,0.13491, 0.067455},{1,-1.14298, 0.4128}},
//         Diff_GY={{0.067455,0.13491, 0.067455},{1,-1.14298, 0.4128}},
//				 Diff_GZ={{0.067455,0.13491, 0.067455},{1,-1.14298, 0.4128}};
Diff_ANGLE Diff_Yaw;
Diff_RAW Diff_D = {{1, 2, 1}, {1, 0.6202, 0.2404}};
Diff_PI Diff_pi,

		//Diff_pd={{20.6341,-20.3415},{1.0000,-0.9512}},//6 0.3
		Diff_pd = {{13.7561, -13.5610}, {1.0000, -0.9512}}, //4.5 0.4
		//Diff_pd={19.1341,-18.9146,{1.0000,-0.9512}},//4.5 0.3
		Diff_angle = {5.9505, -5.9307, 1.0000, -0.9802};
Diff_PID Diff_pid;
/************  ÍÓÂÝÒÇµÍÍ¨ÂË²¨²ÎÊý *************/
const float NUM[3] = {0.029955, 0.059909, -0.029955};
const float DEN[3] = {1, -1.45424, 0.57406};
/************ ÁãÆ¯¸ßÍ¨ÂË²¨²ÎÊý *************/
const float NUM1[3] = {0.99778, -1.99556, 0.99778};
const float DEN1[3] = {1, -1.99556, 0.99557}; //0.25

/************ pid²¹³¥²ÎÊý *************/

const float NUM_PI[2] = {75.3000, -74.1938}; //10%
//const float  NUM_PD[2] = {5.6016,-5.5493};    //10%
//
//const float  DEN_PD[2] = {1.0000, -0.9881};    //10%

const float NUM_PID[3] = {15.4744, 0.0128, -15.4617}; //
const float DEN_PID[3] = {1.0000, -0.0009, -0.9991};	//

//const float  NUM_PID[3] = {10.7734,0.0089,-10.7645};    //
//const float  DEN_PID[3] = {1.0000,-0.6082,-0.3918};    //

const float NUM_PD[2] = {7.4762, -6.8095}; //7
const float DEN_PD[2] = {1.0000, -0.9048}; //0.008

//const float  NUM_PD[2] = {8.7619,-8.0000};    //8
//const float  DEN_PD[2] = {1.0000,-0.9048};    //0.008

//const float  NUM_PD[2] = {10.7619,-9.8095};    //10
//const float  DEN_PD[2] = {1.0000,-0.9048};    //0.007

/************  ÍÓÂÝÒÇµÍÍ¨ÂË²¨º¯Êý *************/
int diff_convert(int init_data, Diff_RAW *imu_type)
{
	imu_type->x_now = init_data;

	imu_type->y_now = (int)(imu_type->NUM[0] * imu_type->x_now + imu_type->NUM[1] * imu_type->x_last + imu_type->NUM[2] * imu_type->x_next - imu_type->DEN[1] * imu_type->y_last - imu_type->DEN[2] * imu_type->y_next);

	imu_type->y_next = imu_type->y_last;
	imu_type->y_last = imu_type->y_now;
	imu_type->x_next = imu_type->x_last;
	imu_type->x_last = imu_type->x_now;
	return imu_type->y_now;
}
/************ ÁãÆ¯¸ßÍ¨ÂË²¨º¯Êý *************/
float diff_convert_yaw(float init_data, Diff_ANGLE *imu_type)
{
	imu_type->x_now = init_data;
	imu_type->y_now = NUM1[0] * imu_type->x_now + NUM1[1] * imu_type->x_last + NUM1[2] * imu_type->x_next - DEN1[1] * imu_type->y_last - DEN1[2] * imu_type->y_next;
	imu_type->y_next = imu_type->y_last;
	imu_type->y_last = imu_type->y_now;
	imu_type->x_next = imu_type->x_last;
	imu_type->x_last = imu_type->x_now;
	return imu_type->y_now;
}
/************ pid²¹³¥²ÎÊý *************/
float diff_convert_PI(float current, float expect, Diff_PI *imu_type)
{
	imu_type->x_now = expect - current;
	imu_type->y_now = NUM_PI[0] * imu_type->x_now + NUM_PI[1] * imu_type->x_last + imu_type->y_last;
	imu_type->y_last = imu_type->y_now;
	imu_type->x_last = imu_type->x_now;
	return imu_type->y_now;
}
float diff_convert_PD(float current, float expect, Diff_PI *imu_type)
{
	imu_type->x_now = expect - current;
	imu_type->y_now = imu_type->NUM[0] * imu_type->x_now + imu_type->NUM[1] * imu_type->x_last - imu_type->DEN[1] * imu_type->y_last;
	imu_type->y_last = imu_type->y_now;
	imu_type->x_last = imu_type->x_now;
	return imu_type->y_now;
}
float diff_convert_PID(float current, float expect, Diff_PID *imu_type)
{
	imu_type->x_now = expect - current;
	imu_type->y_now = NUM_PID[0] * imu_type->x_now + NUM_PID[1] * imu_type->x_last1 + NUM_PID[2] * imu_type->x_last2 - DEN_PID[1] * imu_type->y_last1 - DEN_PID[2] * imu_type->y_last2;
	imu_type->y_last2 = imu_type->y_last1;
	imu_type->y_last1 = imu_type->y_now;
	imu_type->x_last2 = imu_type->x_last1;
	imu_type->x_last1 = imu_type->x_now;
	return imu_type->y_now;
}
